version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3.8.0-management
    ports:
      - '5672:5672'
      - '15672:15672'


  course.api:
    image: ${DOCKER_REGISTRY-}courseapi
    build:
      context: .
      dockerfile: Course.Api/Dockerfile
    links:
      - rabbitmq
    ports:
      - '5000:5000'
    restart: on-failure   
    depends_on:
      - rabbitmq     
    
  course.feedback:
    image: ${DOCKER_REGISTRY-}coursefeedback
    build:
      context: .
      dockerfile: Course.Feedback/Dockerfile
    links:
      - rabbitmq
    ports:
      - '6000:6000'
    restart: on-failure    
    depends_on:
      - rabbitmq    


  course.files:
    image: ${DOCKER_REGISTRY-}coursefiles
    build:
      context: .
      dockerfile: Course.Files/Dockerfile
    links:
      - rabbitmq
    ports:
      - '7000:7000'
    restart: on-failure    
    depends_on:
      - rabbitmq    


  course.identity:
    image: ${DOCKER_REGISTRY-}courseidentity
    build:
      context: .
      dockerfile: Course.Identity/Dockerfile
    links:
      - rabbitmq
    ports:
      - '8000:8000'
    restart: on-failure 
    depends_on:
      - rabbitmq


  course.notification:
    image: ${DOCKER_REGISTRY-}coursenotification
    build:
      context: .
      dockerfile: Course.Notification/Dockerfile
    links:
      - rabbitmq
    ports:
      - '9000:9000'
    restart: on-failure 
    depends_on:
      - rabbitmq
  
  course.gateway:
    image: ${DOCKER_REGISTRY-}coursegateway
    build:
      context: .
      dockerfile: Course.Gateway.Ocelot/Dockerfile
    ports:
      - '10000:80'
    restart: on-failure
    links:
      - course.api
      # - course.notification
      # - course.identity
      # - course.files
      # - course.feedback